### ISSUE TITLE
Creating splash screen with the app icon in the root folder.

### ISSUE THREAD

**Issue by yuvrajsinghgmx** [yuvrajsinghgmx/ShopSmart#1]

**Comment by akeelshafi** [comment]
i want to contribute to this issue

**Comment by yuvrajsinghgmx** [comment]
@akeelshafi  you can contribute to #3 if yes then ask for assign request there.

**Comment by yuvrajsinghgmx** [comment]
@Satyajit0003 Logo files are uploaded in the root directory.

**Comment by Satyajit0003** [comment]
okk

**Comment by yuvrajsinghgmx** [comment]
Anu Update ??

**Comment by Avinash-Codes** [comment]
Sir, I want to contribute to this and help solve the issue as quickly as possible.

**Comment by Satyajit0003** [comment]
> Any Update ?? @Satyajit0003 

Working on it
