### ISSUE TITLE
Update Bottom Bar to Align with New App UI

### ISSUE THREAD

**Issue by Avinash-Codes** [yuvrajsinghgmx/ShopSmart#103]
Description:
We need to redesign the bottom navigation bar to match the new user interface of the app. This update will enhance the overall user experience and ensure consistency across the app's design.

Feature Details:
Design Update: Revise the current bottom navigation bar to align with the new UI components and color scheme.
Iconography: Update icons to ensure they are modern and visually appealing, matching the app’s aesthetic.

**Comment by Avinash-Codes** [comment]
Please Assign me this

**Comment by Avinash-Codes** [comment]
> please assign me this

i am working on this !

**Comment by yuvrajsinghgmx** [comment]
@aahanajena You may create a new issue or feature request.

**Comment by Avinash-Codes** [comment]
who pushed this file its having some error
please fix this
![Screenshot 2024-10-25 120314](https://github.com/user-attachments/assets/dd92779b-80d8-4376-bdaa-5c6a4f674877)

**Comment by yuvrajsinghgmx** [comment]
Hey @Avinash-Codes I checked the original and even a clone of the repo both are getting build successfully the code had some issues but  i had fixed it.
I think there is some issue in your forked repo.

![image](https://github.com/user-attachments/assets/63323931-be7e-4c36-8470-06cbc65eea94)

**Comment by Avinash-Codes** [comment]
Done With This
