### ISSUE TITLE
Revise Existing Account Section to Align with New App UI

### ISSUE THREAD

**Issue by Avinash-Codes** [yuvrajsinghgmx/ShopSmart#104]
Description:
The current account section of the app appears outdated and does not align with the new app UI. This issue aims to modernize the account section to provide a more cohesive user experience.

Feature Details:
UI Update: Redesign the account section to match the new app’s aesthetic, including colors, fonts, and layout.

**Comment by yuvrajsinghgmx** [comment]
@Avinash-Codes Any Update as other contributors are asking for assignment,

**Comment by Avinash-Codes** [comment]
> @Avinash-Codes Any Update as other contributors are asking for assignment,

"Yes, I was working on this, and my exam just finished yesterday

**Comment by Avinash-Codes** [comment]
done with this!
