### ISSUE TITLE
Backend of "Continue with Google"

### ISSUE THREAD

**Issue by iAmAjayTeli** [yuvrajsinghgmx/ShopSmart#105]
I want to do the backend of the "continue with google" part which are present in the signup screen.

![signup (new)](https://github.com/user-attachments/assets/feaf0ec0-5250-441f-83dc-d215bd4c375e)

@yuvrajsinghgmx please assign me, i will do that

**Comment by yuvrajsinghgmx** [comment]
@iAmAjayTeli This is going to be One Tap google login have you done it previously in any other app.

**Comment by iAmAjayTeli** [comment]
@yuvrajsinghgmx  yaa i have done in  my many project

**Comment by yuvrajsinghgmx** [comment]
@iAmAjayTeli Should I assign this to you ??

**Comment by yuvrajsinghgmx** [comment]
Please reply ASAP.

**Comment by iAmAjayTeli** [comment]
@yuvrajsinghgmx sorry you can assign others who are interested

**Comment by yuvrajsinghgmx** [comment]
> @yuvrajsinghgmx sorry you can assign others who are interested

No Worries.
