### ISSUE TITLE
Managing  'backend of Continue with Email'

### ISSUE THREAD

**Issue by Uditya-Raj** [yuvrajsinghgmx/ShopSmart#108]
I want to perform the task of managing backend of Continue with Gmail.
 You can share me the API of your backend or we can do it using firebase  as backend, In this share me access of your firebase account.
 
![img4](https://github.com/user-attachments/assets/48e867d7-ffdd-4658-8a9d-9e64cd170077)

@yuvrajsinghgmx  assign me this task

**Comment by yuvrajsinghgmx** [comment]
Sorry @Uditya-Raj this particular issue has been asked for assignment so please consider creating a new issue or feature request.

**Comment by Uditya-Raj** [comment]
@yuvrajsinghgmx  He @iAmAjayTeli has assigned for UI of Continue with gmail but I am asking for its backend.
If it does not  makes sense then just ignore it , 
@yuvrajsinghgmx I really want to contribute to this project please assign me some task by yourself

**Comment by yuvrajsinghgmx** [comment]
@Uditya-Raj 

Should I assign this to you ??
