### ISSUE TITLE
Feature Request: Add Reorder Handle Button for Shopping List Items

### ISSUE THREAD

**Issue by Ankesh-erek** [yuvrajsinghgmx/ShopSmart#11]
Currently, users of the shopping list app can view items in a static list. This feature request aims to introduce a reorder handle button to allow users to rearrange the items in the shopping list manually.

**Proposed Solution**
   *  Add a reorder handle (e.g., a small drag icon with horizontal lines) next to each item in the shopping list.
   *  Users can press and hold the reorder handle to drag and move items up or down the list.
   *  The reordered list should persist after changes, either by saving the new order in the database or retaining the order while the app is active.
     **I am confident that I can implement this feature to enhance the user experience by allowing item reordering in the shopping list.**
**Could I please be assigned to this issue?  Also, could you kindly add the @GSSOC tag and the appropriate level tag? Thank you!**

**Comment by AnleaMJ** [comment]
I'd like to work on this @Ankesh-erek. Please assign this to me with appropriate gssoc-ext tags. Thank you.

**Comment by yuvrajsinghgmx** [comment]
@Ankesh-erek any update on this ??

**Comment by Ankesh-erek** [comment]
@yuvrajsinghgmx I apologize for the inconvenience sir, but due to my mid-semester exams, I was unable to complete the task on time. I assure you that I will have it finished by tomorrow evening. Thank you for your understanding.

**Comment by yuvrajsinghgmx** [comment]
No Worries @Ankesh-erek .
