### ISSUE TITLE
Modify UI of the Profile section 

### ISSUE THREAD

**Issue by iAmAjayTeli** [yuvrajsinghgmx/ShopSmart#118]
I want to fully  modify the UI of the profile section according to the new UI #4 

@yuvrajsinghgmx please assign me to do this

**Comment by yuvrajsinghgmx** [comment]
This issue has been assigned already
iin #104.

**Comment by iAmAjayTeli** [comment]
okay @yuvrajsinghgmx

**Comment by iAmAjayTeli** [comment]
This issue is already has been assigned to someone else
