### ISSUE TITLE
Text View Overlaps with Notch Area on Modern Smartphones

### ISSUE THREAD

**Issue by Ankesh-erek** [yuvrajsinghgmx/ShopSmart#12]
In the current layout of the app, the ShopSmart text at the top is partially hidden by the notch or camera area of smartphones with a notch-type display. This issue occurs due to the text being placed too close to the top edge of the screen, which causes it to overlap with the system UI.
**I would like to work on resolving this issue. Could I please be assigned to this issue? Also, could you kindly add the @GSSOC tag and the appropriate level tag? Thank you!?**

**Comment by AnleaMJ** [comment]
I'd like to work on this @Ankesh-erek. Please assign this to me with appropriate gssoc-ext tags. Thank you.

**Comment by yuvrajsinghgmx** [comment]
@AnleaMJ You may create new issue or a feature request.

**Comment by yuvrajsinghgmx** [comment]
This issue is resolved.
