### ISSUE TITLE
Documentation: Wanted To Add Contributing.md

### ISSUE THREAD

**Issue by milansamuel609** [yuvrajsinghgmx/ShopSmart#121]
I wanted to add the contributing.md file which will help the contributors to easily contribute. It will also help them understand the correct way of following coding practices and other important things.

Wanted to do the following changes :-

1) Enhance the project structure
2) Add the section of this may help
3) Add project structure section
4) Add additional method of contributing through GitHub desktop section
5) Add good coding practices section
6) Add the help and support section
7) Add the pull request section
8) Add issue report process section
9) Add thank you section

**Comment by yuvrajsinghgmx** [comment]
This has been done already.
