### ISSUE TITLE
Add CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by Nikhil0-3** [yuvrajsinghgmx/ShopSmart#122]
A code of conduct helps maintain a respectful and welcoming community. Without it, contributors may not know what behavior is expected.

**Comment by Nikhil0-3** [comment]
I added CODE_OF_CONDUCT.md file.
Since this is my first contribution ,If any Changes required please tell.

**Comment by yuvrajsinghgmx** [comment]
@Nikhil0-3 Please create PR.

**Comment by Nikhil0-3** [comment]
i have updated the file and added the PR. Please check and tell me if any further changes required.
