### ISSUE TITLE
Enhance UI of profile screen 

### ISSUE THREAD

**Issue by Shreyansh1563** [yuvrajsinghgmx/ShopSmart#126]
@yuvrajsinghgmx In issue #4 the UI of the profile screen looks like this ⬇️ which is more classy.
![betterProfileUI](https://github.com/user-attachments/assets/974863bd-721f-46cc-94b0-f6a8400ca3d7)
but your current UI of profile screen looks like this
![currentProfileUI](https://github.com/user-attachments/assets/51f981c4-ee6d-4581-b117-c7b14547505d)

@yuvrajsinghgmx  please assign this issue to me

**Comment by Shreyansh1563** [comment]
@yuvrajsinghgmx  this issue was already fixed by someone

**Comment by yuvrajsinghgmx** [comment]
For further improvements I had assigned this to you.
