### ISSUE TITLE
Feature]: Automated project structure updation using github workflows, python scripts and action bot

### ISSUE THREAD

**Issue by J-B-Mugundh** [yuvrajsinghgmx/ShopSmart#129]
### Feature Description

Automated project structure updation using github workflows, python scripts and action bot

### Use Case

Currently, we dont have the automated project structure updation in our repository. 

### Benefits

It'll be benefitial for the new commers to understand the project structure from readme itself and reduces the manual work as well. 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/26bbda18-4082-4d17-8222-1488fbcdb3fb)

**Comment by J-B-Mugundh** [comment]
@yuvrajsinghgmx Please assign me this issue. It'll really be worthy and reduces a lot of everyday manual work. Also add gssoc-extd, hacktoberfest and level labels..

**Comment by J-B-Mugundh** [comment]
@yuvrajsinghgmx Could u please increase to level2 atleast? The similar feature got level 2 and 3 as well in someother contributions.

**Comment by yuvrajsinghgmx** [comment]
According to the guidelines this contribution is for level 1.

**Comment by J-B-Mugundh** [comment]
> According to the guidelines this contribution is for level 1.

Oh. But our program manager has given level2 for the same, bro. https://github.com/recodehive/machine-learning-repos/issues/1505

**Comment by yuvrajsinghgmx** [comment]
> > According to the guidelines this contribution is for level 1.
> 
> Oh. But our program manager has given level2 for the same, bro. [recodehive/machine-learning-repos#1505](https://github.com/recodehive/machine-learning-repos/issues/1505)

No Problem @J-B-Mugundh GO Ahead. Good Luck  👍👍👍
