### ISSUE TITLE
Feature Request: Add "Shopping Completed" Button to Ensure All Items Are Checked

### ISSUE THREAD

**Issue by Ankesh-erek** [yuvrajsinghgmx/ShopSmart#13]
When there are too many items in the shopping list, it's possible to accidentally miss some items while checking them off. To avoid this, I propose adding a "Shopping Completed" button at the bottom of the list that will check.
Feature Details: -
 *  Add a button labeled "Shopping Completed" at the bottom of the list.
 *  On clicking this button:
          -- If any items are unchecked, show a warning: "You missed some item."
          -- If all items are checked, show a success message: "Shopping done!"
**Could I please be assigned to this issue? Also, could you kindly add the @GSSOC tag and the appropriate level tag? Thank you!**

**Comment by yuvrajsinghgmx** [comment]
Any Update ??

**Comment by shivin21** [comment]
i want to work on this issue please assign me.

**Comment by Ankesh-erek** [comment]
Mine is about to complete @shivin21  brother

**Comment by yuvrajsinghgmx** [comment]
@shivin21 You may create a new issue or a suggest a feature.

**Comment by Ankesh-erek** [comment]
Hello @yuvrajsinghgmx sir , please help me with this . I can't push my feature. 
I also created a different branch for it.

![IMG_20241006_200825206.jpg](https://github.com/user-attachments/assets/fee67770-8e33-4ddc-866a-222309bf57a0)

![IMG_20241006_200816864_HDR.jpg](https://github.com/user-attachments/assets/5e598e84-2298-4231-b3cc-52cc47310e01)

**Comment by Ankesh-erek** [comment]
I also pushed a feature previously but I never faced any problem but this time ......😕

**Comment by Ankesh-erek** [comment]
Please help me with this . You can also check this out. https://drive.google.com/file/d/1J-FEx-c5LCZ46dAGIuGc8jmygCok9sMa/view?usp=drivesdk

**Comment by yuvrajsinghgmx** [comment]
You are trying to push directly on my repo but you should push on your forked repo then create a pull request.

**Comment by Ankesh-erek** [comment]
so sorry...i'm doing the minor mistake lol . @yuvrajsinghgmx thank you for the reminding me sir.

**Comment by Ankesh-erek** [comment]
@yuvrajsinghgmx sir , i already sent you a pull request of this issue 2 days before, but it is not merged. What happen?

**Comment by Ankesh-erek** [comment]
Is there any problem?

**Comment by yuvrajsinghgmx** [comment]
The issue was merged and you will get the points for it tooo...And due to some issues in the code i had to revert the pull request I will try to add your code later
.

**Comment by Ankesh-erek** [comment]
ohh....ok got it 👍🏻
