### ISSUE TITLE
Make HomePage  lively.

### ISSUE THREAD

**Issue by yuvrajsinghgmx** [yuvrajsinghgmx/ShopSmart#135]
The homepage of our app seems very static and doesn't seem very engaging make it lively and show some creativity.

Contributors are requested to share their idea while asking for assign request.
I am giving this a level3 because i expect something creative.

**Comment by EvanSingee** [comment]
can you assign this to me bhaiya?
@yuvrajsinghgmx

**Comment by yuvrajsinghgmx** [comment]
@EvanSingee Any update on this ??
