### ISSUE TITLE
Strengthening ExampleInstrumentedTest.kt

### ISSUE THREAD

**Issue by EvanSingee** [yuvrajsinghgmx/ShopSmart#142]
ISSUES:
- Limited Tests
- Hardcoded Strings
- Naming Conventions
- Commenting

BETTERMENT:
-Expand Test Coverage
-Improve Error Messages
-Use Constants for Values
-Naming & Documentation

**Comment by EvanSingee** [comment]
Pls help me contribute @yuvrajsinghgmx

**Comment by yuvrajsinghgmx** [comment]
> Pls help me contribute @yuvrajsinghgmx

Sorry @EvanSingee my exam are on so i will not be able to help you but still you can ask anything if you get stuck somewhere.

@Muhasif-Hafiz Would you be able to help him in this ??

**Comment by EvanSingee** [comment]
I just wanted you to help in assigning the issue. 
Thanks for it @yuvrajsinghgmx 
I'll do it by myself and PR by tomorrow.
Pls do add labels for the same issue.

**Comment by Muhasif-Hafiz** [comment]
@yuvrajsinghgmx okay i will take care about it
