### ISSUE TITLE
Fix Minor issues Such as Naming Conventions, Hardcoded Strings etc

### ISSUE THREAD

**Issue by Muhasif-Hafiz** [yuvrajsinghgmx/ShopSmart#144]
ISSUES:

Limited Tests
Hardcoded Strings
Naming Conventions
Commenting
BETTERMENT:
-Expand Test Coverage
-Improve Error Messages
-Use Constants for Values
-Naming & Documentation

**Comment by Muhasif-Hafiz** [comment]
> ISSUES:
> 
> Limited Tests Hardcoded Strings Naming Conventions Commenting BETTERMENT: -Expand Test Coverage -Improve Error Messages -Use Constants for Values -Naming & Documentation

@EvanSingee Do it

**Comment by EvanSingee** [comment]
Gssoc ext. Label isn't mentioned.
@Muhasif-Hafiz 
And can you make it to level 2 issue?

**Comment by Muhasif-Hafiz** [comment]
no  this is level 1 issue

**Comment by Muhasif-Hafiz** [comment]
@EvanSingee go ahead!

**Comment by EvanSingee** [comment]
Thanks for assigning @Muhasif-Hafiz
