### ISSUE TITLE
UI enhancement for Single item in Shopping Item lists.

### ISSUE THREAD

**Issue by ShahanasParapporu** [yuvrajsinghgmx/ShopSmart#145]
The current Single item UI in the recycler view for shopping list looks like this:
![shopping_list_currentimg](https://github.com/user-attachments/assets/e37f51e1-784a-4667-badd-a767fcbf445a)

I would like to change the Item Card UI to look like:
![to change shopping list item Ui](https://github.com/user-attachments/assets/bf19f2f8-d45b-4386-bcde-c1d8e8c95906)

I will add the increment-decrement buttons, No of items text, change styling for item view , add the description text and generate the same styling for the item views by including the Added date.

Could you please assign this issue to me under GSSOC'24 extd?

**Comment by yuvrajsinghgmx** [comment]
@ShahanasParapporu Are You facing any issue ??
