### ISSUE TITLE
Enhance UI Design for Improved Visual Appeal and User Engagement

### ISSUE THREAD

**Issue by Avinash-Codes** [yuvrajsinghgmx/ShopSmart#15]
Issue: The current user interface (UI) of the application appears too minimal and lacks visual attractiveness, which may affect user engagement and overall experience.

**Comment by Avinash-Codes** [comment]
Please Assign this to me

**Comment by yuvrajsinghgmx** [comment]
@Avinash-Codes When User opens keyboard the  list goes out of screen please check if it can be fixed.

**Comment by Avinash-Codes** [comment]
> @Avinash-Codes When User opens keyboard the list goes out of screen please check if it can be fixed.

okh

**Comment by Avinash-Codes** [comment]
> @Avinash-Codes When User opens keyboard the list goes out of screen please check if it can be fixed.

i am removing that design and making it more attractive somewhat like this its half done 
![Screenshot 2024-10-02 211856](https://github.com/user-attachments/assets/712a7111-ede1-4587-a4f9-d16e752ab668)

**Comment by yuvrajsinghgmx** [comment]
Make sure you use Android Ladybud and latest AGP.

**Comment by Avinash-Codes** [comment]
> Make sure you use Android Ladybud and latest AGP to avoid any merge conflicts.

OK!

**Comment by Avinash-Codes** [comment]
Made the Pull request please see there are some conflicts

**Comment by Avinash-Codes** [comment]
is it resolved and merged ?

**Comment by yuvrajsinghgmx** [comment]
Yes I did it sync the repo.
