### ISSUE TITLE
Add CONTRIBUTION.md File for Contribution Guidelines

### ISSUE THREAD

**Issue by a-n-u-vanguri** [yuvrajsinghgmx/ShopSmart#151]
Description:

Currently, there are no specific contribution guidelines documented in a separate CONTRIBUTION.md file. This can cause confusion for new contributors on how to properly contribute to the project. The addition of a CONTRIBUTION.md file will help standardize contributions and ensure that everyone follows the same process.

Expected Changes:

- [ ] Create a CONTRIBUTION.md file in the root directory of the project.
- [ ] Include clear guidelines for contributing to the repository, such as:
- [ ] Steps for forking the repo and making changes.
- [ ] How to create and submit a pull request.
- [ ] Guidelines for writing commits and pull request descriptions.
- [ ] Coding standards (formatting, best practices).
- [ ] How to report issues or feature requests.
- [ ] Reference to the Code of Conduct.

Additional Context:

This will help streamline the contribution process, making it easier for contributors to understand the expectations and follow the correct procedure.

Thank you :)

**Comment by yuvrajsinghgmx** [comment]
Hi! @a-n-u-vanguri 

There exists a contributor guidelines file check the readme once again.
You can suggest improvements to it.

**Comment by a-n-u-vanguri** [comment]
Nope! . It's perfectly good . I didn't checked properly my mistake.
