### ISSUE TITLE
Adding the merices table

### ISSUE THREAD

**Issue by Aman-G-upta** [yuvrajsinghgmx/ShopSmart#153]
Adding the merices table to the readme file
@yuvrajsinghgmx , please assign me under this issue !!!

![Screenshot 2024-10-26 185138](https://github.com/user-attachments/assets/fcb2c7d5-9988-4b53-be5e-677919c9afd0)

**Comment by yuvrajsinghgmx** [comment]
This has been already implemented in Contributors guide.

**Comment by Aman-G-upta** [comment]
Ensuring programs are perfectly
So please assing me under this issue @yuvrajsinghgmx
