### ISSUE TITLE
Animated Splash Screen

### ISSUE THREAD

**Issue by yuvrajsinghgmx** [yuvrajsinghgmx/ShopSmart#158]
NOT A VIDEO.

**Comment by Gopal0Gupta** [comment]
@yuvrajsinghgmx i want to work on it
please assign it to me

**Comment by yuvrajsinghgmx** [comment]
@Gopal0Gupta Any Update??

**Comment by Gopal0Gupta** [comment]
> @Gopal0Gupta Any Update??

Sorry for Delay, it will take few more days as i am not getting time due to festivals, if someone else wants to work please assign this issue to them

**Comment by yuvrajsinghgmx** [comment]
Should i wait ??

**Comment by Gopal0Gupta** [comment]
> Should i wait ??

yes, please
