### ISSUE TITLE
Add Swiping Functionality for deleting the item in the shopping list 

### ISSUE THREAD

**Issue by ShahanasParapporu** [yuvrajsinghgmx/ShopSmart#167]
I would like to add the functionality of swiping right/left for the shopping item's list, so that the item can be deleted and not shown again under this list.

I have added the PR for the new item design. I can work on this functionality once the PR created for the new shopping list item design has been merged and verified.

The below is the list where i can add this functionality:
![new_shoppinglist_ui](https://github.com/user-attachments/assets/baa1524e-1ffb-4529-bf67-22c63911e214)

Can you assign this issue to me under GSSOC'24 extd?

**Comment by yuvrajsinghgmx** [comment]
@ShahanasParapporu Are you facing any issue ??

**Comment by ShahanasParapporu** [comment]
Dear Yuvraj,

I have added the functionality till swiping and deleting the item, however
I am facing some challenges in rendering the refreshed recycler view.

The thing is I am on a company trip which is causing the delay.

I will be able to complete the feature only next week.


Thank you
