### ISSUE TITLE
 Thank You and Happy Diwali! 🌟

### ISSUE THREAD

**Issue by yuvrajsinghgmx** [yuvrajsinghgmx/ShopSmart#175]
Hola, amigos

As our open-source event is coming to an end, I want to take a moment to express my heartfelt gratitude for your contributions. Your hard work, dedication, and creativity have made a significant impact on this project, and I am truly thankful for each of you.

As we celebrate Diwali in just two days, I wish you all a very Happy Diwali! May this festival of lights bring joy, prosperity, and success to you and your families. 🌼✨

I encourage each of you to share your achievements and this [repository ](https://github.com/yuvrajsinghgmx/ShopSmart)on your social media and leave a 🌟 if ShopSmart added a little bit of smartness and value to you. Let’s spread the word about our amazing work and inspire others to join our journey!

Thank you once again for being a part of this incredible community. Enjoy the festivities!

**Comment by pratheekv39** [comment]
@yuvrajsinghgmx This might be one of the best projects I’ve contributed to in GSSoC. I had a lot of fun working on it! Even beyond the event, I’d love to continue contributing to your repository. Happy Diwali to everyone who has contributed, directly or indirectly! :)

**Comment by yuvrajsinghgmx** [comment]
@Avinash-Codes
@iAmAjayTeli
@yasheela-alla
@Shreyansh1563
@rajdeepchakraborty-rc
@Yashvardhan-17
@Farhan-Ahmad01
@EvanSingee
@Satyajit0003
@J-B-Mugundh
@Nikhil0-3
@ark0078
@AnleaMJ
@Aman-G-upta
@Ankesh-erek
@Rohityadav9575
@Varsha567
@AndroidLord
@23WH1A0507
@KiranBaliga
@milansamuel609
@Muhasif-Hafiz
@rees8
@Shariq2003
@Shasha004
@aditya07389
...

**Comment by milansamuel609** [comment]
> Hola, amigos
> 
> As our open-source event is coming to an end, I want to take a moment to express my heartfelt gratitude for your contributions. Your hard work, dedication, and creativity have made a significant impact on this project, and I am truly thankful for each of you.
> 
> As we celebrate Diwali in just two days, I wish you all a very Happy Diwali! May this festival of lights bring joy, prosperity, and success to you and your families. 🌼✨
> 
> I encourage each of you to share your achievements and this [repository ](https://github.com/yuvrajsinghgmx/ShopSmart)on your social media and leave a 🌟 if ShopSmart added a little bit of smartness and value to you. Let’s spread the word about our amazing work and inspire others to join our journey!
> 
> Thank you once again for being a part of this incredible community. Enjoy the festivities!

Thank you very much and also a very happy diwali 🎇🪔

**Comment by Shariq2003** [comment]
Happy Diwali @yuvrajsinghgmx and everyone

**Comment by rajdeepchakraborty-rc** [comment]
@yuvrajsinghgmx Hola!

Thank you so much for your kind words! It's been an incredible journey working alongside such talented individuals. I'm grateful for the opportunity to contribute to this project. Thanks for your hard work in reviewing all the PRs and going through tons of issues each day. You alongside the other admins and mentors are responsible for making the process smooth for us.

Wishing you all a very Happy Diwali! May this festive season bring joy and prosperity to you and your loved ones too. 🌟✨

It was great contributing to ShopSmart and have already started the repository! Let’s keep coding and inspiring each other!

Thanks again, and enjoy the celebrations!

**Comment by aditya07389** [comment]
Thankyou for the opportunity @yuvrajsinghgmx 
Hoping to continue contributing to this project . 
Happy diwali 🌟✨

**Comment by EvanSingee** [comment]
Thanks @yuvrajsinghgmx 
all the brainstorming issues, code solutions, excitement for a merged PR in the morning were all memories for my life.
This being my first repo worked on Github feels even more special.
Happy Diwali everyone guys!🌟

**Comment by Avinash-Codes** [comment]
@yuvrajsinghgmx 
Hola! 🎉

Thank you for the warm message and the opportunity to be part of this open-source journey with ShopSmart. It’s been an incredible experience collaborating with such talented and driven individuals. I’m grateful for the chance to contribute, learn, and grow together.

Wishing everyone a bright and joyful Diwali! May this festival fill your homes with light and your lives with happiness and success. 🌟✨

Happy Diwali to all, and thank you once again for this inspiring journey!

**Comment by Muhasif-Hafiz** [comment]
@yuvrajsinghgmx aren't we going to get any certificate

**Comment by pratheekv39** [comment]
@Muhasif-Hafiz Program ends on 10th November....If you have gained 60 points , you will get a certificate
