### ISSUE TITLE
Implementation of Support & Help Settings 

### ISSUE THREAD

**Issue by pratheekv39** [yuvrajsinghgmx/ShopSmart#181]
I will Implement the following components in it:
1) FAQ Center
2)Chat Support
3)Report an Issue
4)Feedback Center

@yuvrajsinghgmx Kindly assign this issue to me after you have reviewed the sent PR ... Thanks :)

**Comment by yuvrajsinghgmx** [comment]
> I will Implement the following components in it:
> 1) FAQ Center
> 2)Chat Support
> 3)Report an Issue
> 4)Feedback Center
> 
> @yuvrajsinghgmx Kindly assign this issue to me after you have reviewed the sent PR ... Thanks :)

I'll take care.

**Comment by yuvrajsinghgmx** [comment]
> <img alt="image" width="235" src="https://private-user-images.githubusercontent.com/165366548/381202335-da1c9650-0f8c-4a43-9f1a-e9afabc062a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMTczNTcsIm5iZiI6MTczMDIxNzA1NywicGF0aCI6Ii8xNjUzNjY1NDgvMzgxMjAyMzM1LWRhMWM5NjUwLTBmOGMtNGE0My05ZjFhLWU5YWZhYmMwNjJhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxNTUwNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzQ4Y2VkMDliYTNmN2E5NTMxNDkzMWQ2Yjc5MzQ4MTgwM2Y1ZGU2NDAzNmFiM2UxN2FiMWFlYTYzYjQ5ODRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YmBSKtKuGxRc6LzbiXsZXorrUtq-bvllfPjJhngzQoI">
> Will there be no issues with the leaderboard ?? Can you add me to assignees just to be safe for this as well as the current issue #183

No it would not have caused any issue you can create PR even without creating an issue.
