### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by yuvrajsinghgmx** [yuvrajsinghgmx/ShopSmart#184]

**Comment by pratheekv39** [comment]
@yuvrajsinghgmx I can do it . Just tell me what do you want me to update and I will work on it ...

**Comment by yuvrajsinghgmx** [comment]
> @yuvrajsinghgmx I can do it . Just tell me what do you want me to update and I will work on it ...

The Screenshots of the app and the features Update.

**Comment by pratheekv39** [comment]
@yuvrajsinghgmx Okay ... I will work on it 👍🏼

**Comment by pratheekv39** [comment]
I will provide you a list of photos with numbers . Kindly , tell me which of these features  would you like me to update :

1) 
![Screenshot_2024-10-30-20-19-56-47_2e866dd9837e72077c6daae78cc2bc15](https://github.com/user-attachments/assets/14b8b6a7-1705-4122-bac6-15dac04e186e)


2)

![Screenshot_2024-10-30-20-21-21-45_2e866dd9837e72077c6daae78cc2bc15](https://github.com/user-attachments/assets/ca5ec2fd-a24c-424d-9a82-612a361b1954)


3)

![Screenshot_2024-10-30-20-24-01-51_2e866dd9837e72077c6daae78cc2bc15](https://github.com/user-attachments/assets/49d29647-b85f-4cad-9d81-9f4c1cfed13a)


4)

![Screenshot_2024-10-30-20-24-16-15_2e866dd9837e72077c6daae78cc2bc15](https://github.com/user-attachments/assets/cca902e9-2c19-40cb-b27e-1182d4ba23b3)


5)

![Screenshot_2024-10-30-20-25-21-31_2e866dd9837e72077c6daae78cc2bc15](https://github.com/user-attachments/assets/c2cd21d9-a1ae-488e-b2e3-56d5e6364890)


6)
![Screenshot_2024-10-30-20-26-38-37_2e866dd9837e72077c6daae78cc2bc15](https://github.com/user-attachments/assets/3f730bc4-3453-4a5e-ae10-389ffbc5b604)

7)

![Screenshot_2024-10-30-20-27-12-52_2e866dd9837e72077c6daae78cc2bc15](https://github.com/user-attachments/assets/ccbca42c-578e-4935-9217-4d1c32d8500f)


8)
![Screenshot_2024-10-30-20-27-26-38_2e866dd9837e72077c6daae78cc2bc15](https://github.com/user-attachments/assets/44bb20cc-311c-48a0-95b2-073ba6d697ad)



9)

![Screenshot_2024-10-30-20-27-40-51_2e866dd9837e72077c6daae78cc2bc15](https://github.com/user-attachments/assets/00666172-0f05-4914-a28d-2d471ac288ea)


10)

![Screenshot_2024-10-30-20-27-51-58_2e866dd9837e72077c6daae78cc2bc15](https://github.com/user-attachments/assets/43a7f3da-13ca-4221-9a63-6ea0f38f0beb)

**Comment by yuvrajsinghgmx** [comment]
Choose whatever you want 😄😄
