### ISSUE TITLE
Adding Dark theme and Light theme colors.

### ISSUE THREAD

**Issue by yuvrajsinghgmx** [yuvrajsinghgmx/ShopSmart#2]
Colors are to be added in the theme file.

**Comment by Satyajit0003** [comment]
i want to work on it 
![Screenshot 2024-10-01 172951](https://github.com/user-attachments/assets/9bf603a2-be9c-442d-822a-c0859a9219e6)

**Comment by Satyajit0003** [comment]
it not visible while add item in dark theme ,so add material theme

**Comment by akeelshafi** [comment]
I’m Akeel, a 3rd-year CSE student with experience in Android development using Kotlin, Jetpack Compose, and libraries like Retrofit, Room, and Firebase. I’d love to work on the issue
