### ISSUE TITLE
Implementing the Bank Accounts Section

### ISSUE THREAD

**Issue by pratheekv39** [yuvrajsinghgmx/ShopSmart#202]
![WhatsApp Image 2024-11-01 at 18 42 19_68f422d8](https://github.com/user-attachments/assets/1a5bcfc0-5405-4e1f-88ba-dd5a53aacccf)

@yuvrajsinghgmx I will add multiple options to manage , add and segregate various  bank accounts and validate them . 
Kindly assign this issue and I'll start working on it immediately . Thanks :)

**Comment by pratheekv39** [comment]
@yuvrajsinghgmx I have fixed the bug now . Can we proceed with this issue now . Kindly , assign after reviewing the sent PR ... Thanks:)

**Comment by pratheekv39** [comment]
@pratheekv39 Can we proceed ?

**Comment by yuvrajsinghgmx** [comment]
I am making some changes will be completed by 9:00 AM after that you can start working on this.

**Comment by yuvrajsinghgmx** [comment]
@pratheekv39 Good to go now.

**Comment by yuvrajsinghgmx** [comment]
Please close the issue  which you have completed.

**Comment by pratheekv39** [comment]
@yuvrajsinghgmx Okay , I will close it from now on👍🏼
