### ISSUE TITLE
ListScreen

### ISSUE THREAD

**Issue by yuvrajsinghgmx** [yuvrajsinghgmx/ShopSmart#212]
Enhance TopBar of the ListScreen and remove the app name.

**Comment by Shreyansh1563** [comment]
@yuvrajsinghgmx  i can do it and also tell me if you have something in mind related to it or i do it on my own.

**Comment by yuvrajsinghgmx** [comment]
Show your creativity.

**Comment by Shreyansh1563** [comment]
@yuvrajsinghgmx you forgot to assign it
