### ISSUE TITLE
Firebase SignIn

### ISSUE THREAD

**Issue by yuvrajsinghgmx** [yuvrajsinghgmx/ShopSmart#215]
Back-end of Continue with Google.

**Comment by Shasha004** [comment]
Can you ,Please assign me this issue.

**Comment by yuvrajsinghgmx** [comment]
Kindly Share your gmail so that i can give you access of the Firebase project.

**Comment by Shasha004** [comment]
> Kindly Share your gmail so that i can give you access of the Firebase project.

sydha7986@gmail.com

**Comment by yuvrajsinghgmx** [comment]
https://console.firebase.google.com/u/0/project/the-shopsmart-ebe5c/overview 

Open this link from your google account this will directly open the prohect.
