### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by yuvrajsinghgmx** [yuvrajsinghgmx/ShopSmart#22]
Add  Screenshots of the app to the readme file and some improvements.

**Comment by Satyajit0003** [comment]
i will make it

**Comment by Avinash-Codes** [comment]
> Add Screenshots of the app to the readme file and some improvements.

FIne will do this as i am having updated repo with new ui integration

**Comment by yuvrajsinghgmx** [comment]
> > Add Screenshots of the app to the readme file and some improvements.
> 
> FIne will do this as i am having updated repo with new ui integration 

According to the guidelines issues are assigned on first come first serve basis so I have assigned @Satyajit0003.

@Avinash-Codes 
You may work on another issue or create a new one

**Comment by yuvrajsinghgmx** [comment]
Now contributors can be assigned to this.

**Comment by Avinash-Codes** [comment]
assign this to me

> Now contributors can be assigned to this.

**Comment by Avinash-Codes** [comment]
I've updated the README file with new features, added new screenshots of the app, and made some improvements.

**Comment by Avinash-Codes** [comment]
I've pushed the code. Please resolve the conflicts and merge it

**Comment by yuvrajsinghgmx** [comment]
Will do it 👍

**Comment by Avinash-Codes** [comment]
Please merge this i am trying to push code for the bottom navigation bar

**Comment by yuvrajsinghgmx** [comment]
> Please merge this i am trying to push code for the bottom navigation bar

Done.
