### ISSUE TITLE
Amazon API

### ISSUE THREAD

**Issue by yuvrajsinghgmx** [yuvrajsinghgmx/ShopSmart#220]
Fetch products on home screen or search screen from Amazon and display on the home page

This PR will get a level 3 and a level 2 both.

**Comment by pratheekv39** [comment]
@yuvrajsinghgmx I can work on it , but it will take time . However, you can get and set up the required API keys and keep it ready. We can implement it once we have the Amazon API keys, endpoints  and have set them up.
