### ISSUE TITLE
Implementing Payment Security Sections

### ISSUE THREAD

**Issue by pratheekv39** [yuvrajsinghgmx/ShopSmart#226]
I will implement the following:
1)Security Scan Section
2)Change Password
3)Privacy Check

@yuvrajsinghgmx Kindly , assign this issue to me... I'll start working on it immediately.. Thanks :)
![WhatsApp Image 2024-11-03 at 14 29 32_0b2fe6eb](https://github.com/user-attachments/assets/8c38c803-0347-4069-8d1f-6b767998a31a)

**Comment by yuvrajsinghgmx** [comment]
Hi @pratheekv39 your previous PR was reverted due to some issues.
You can copy the file contents from PR history and please make a new PR.

**Comment by yuvrajsinghgmx** [comment]
Hi @pratheekv39 the Scaffold is taking too much space in the top and bottom of the screens.

Fix it if you can.

**Comment by pratheekv39** [comment]
@yuvrajsinghgmx For all screens ??

**Comment by yuvrajsinghgmx** [comment]
> @yuvrajsinghgmx For all screens ??

Do it make a PR I will give it a level 3.

**Comment by pratheekv39** [comment]
@yuvrajsinghgmx Ok , I will do it now

**Comment by pratheekv39** [comment]
@yuvrajsinghgmx My PR #225 has been removed from the leaderboard . Can you assign labels to PR #229 instead so that it shows on the leaderboard .Thanks

**Comment by pratheekv39** [comment]
@yuvrajsinghgmx It is visible now , nevermind

**Comment by pratheekv39** [comment]
@yuvrajsinghgmx I will raise another PR for the scaffold . There are many changes to be tested as firebase authentication is added and also the UI of ListScreen is changed....Before that I will complete this issue #226 and then work on scaffold
