### ISSUE TITLE
UpComing Page

### ISSUE THREAD

**Issue by yuvrajsinghgmx** [yuvrajsinghgmx/ShopSmart#34]
- User adds a list for a date in future.
- That particular list automatically shows up on the Home Screen on D-Date.
- List is deleted only after user deletes it manually from the home screen.

**Comment by MonuGit9** [comment]
Can you assign it to me ?

**Comment by yuvrajsinghgmx** [comment]
@MonuGit9 Please do it ASAP.

**Comment by yuvrajsinghgmx** [comment]
Any Update @MonuGit9 ??

**Comment by MonuGit9** [comment]
Till now setted-up the project only.
Provide you update by today evening.

**Comment by Farhan-Ahmad01** [comment]
@MonuGit9 Are you still working on it??

**Comment by MonuGit9** [comment]
> @MonuGit9 Are you still working on it??

Yaa.

**Comment by yasheela-alla** [comment]
hi @yuvrajsinghgmx , since the issue hasnt been solved yet, can i work on it? i had an approach in mind on how to solve issue

**Comment by yuvrajsinghgmx** [comment]
Any update @MonuGit9 ???

**Comment by yasheela-alla** [comment]
@yuvrajsinghgmx @Farhan-Ahmad01 Can i work on this issue?

**Comment by yuvrajsinghgmx** [comment]
@yasheela-alla You may start working on it and if you create your PR before @MonuGit9 your PR will be merged.
As i am getting no response from him.

**Comment by yuvrajsinghgmx** [comment]
@MonuGit9 Please provide any Update ?
 Should I Reassign this issue to someone else ??
