### ISSUE TITLE
Updates,Queries and Suggestions here.

### ISSUE THREAD

**Issue by yuvrajsinghgmx** [yuvrajsinghgmx/ShopSmart#4]
We can discuss implementation of new features here. Please add a comment if you have an out-of-box suggestion and it will be immediately assigned to you if you wanted to work on that particular issue.

Dont Forget to star the repo.

**Comment by Avinash-Codes** [comment]
is this part of hacktoberfest ?

**Comment by yuvrajsinghgmx** [comment]
This project is under GSSOC and GSSOC has  collaborated with Hactoberfest i think.

**Comment by Avinash-Codes** [comment]
okh one question is this your overall app ui isn't ?
![Screenshot 2024-10-02 154218](https://github.com/user-attachments/assets/4a0b0395-3677-40a4-89cd-33bdf98255c2)

**Comment by yuvrajsinghgmx** [comment]
Yes improvements were made to the UI but they were not up to the mark so they were discarded.

**Comment by yuvrajsinghgmx** [comment]
Everyone please update the forked repo once.

**Comment by Avinash-Codes** [comment]
> Everyone please update the forked repo once.

Done

**Comment by MonuGit9** [comment]
I can add the app in dark theme feature.
If want, plz assign me

**Comment by yuvrajsinghgmx** [comment]
Hi @Avinash-Codes @Rohityadav9575 @Satyajit0003 @Ankesh-erek @rees8 

Please Update the repo once.

**Comment by Ankesh-erek** [comment]
@yuvrajsinghgmx done

**Comment by yuvrajsinghgmx** [comment]
@Avinash-Codes Are you busy somewhere ??

**Comment by Avinash-Codes** [comment]
> @Avinash-Codes Are you busy somewhere ??

I was occupied because of some work

**Comment by yuvrajsinghgmx** [comment]
Dear Contributors,  
@Avinash-Codes @pratheekv39 @Satyajit0003 @Farhan-Ahmad01 @ark0078 @Rohityadav9575 @Ankesh-erek @rees8 @Shariq2003 @Amit-4186,

I’m happy to acknowledge the exceptional talent and dedication each of you has shown as coders and contributors. Your adherence to the contributor guidelines and the quality of your work have been exemplary.

I'm reaching out to initiate a discussion on the future trajectory and features of this app. Having a well-defined and visionary direction will not only enhance our collective contributions but also streamline our efforts toward a shared goal.

Please share your best of the idea you may think of for defining future of this app.

I would love to hear your thoughts, so please share your suggestions and ideas here. And feel free to get creative and think big—let’s aim for something complex and forward-thinking!
Comment below 👇.

**Comment by Farhan-Ahmad01** [comment]
Hey @yuvrajsinghgmx, I updated my project but still can't find the add button when the item list is empty. Upon reviewing the code, I discovered that the issue remains unresolved.

**Comment by yuvrajsinghgmx** [comment]
Hello Contributors,

Our app has been facing challenges due to the absence of a predefined UI, which has been increasingly problematic for me as well. Today, I am uploading the new UI, and all future additions and improvements will be based on this design. Please make sure to refer to this UI before adding any new features or making changes.

![ShopSmartUI7](https://github.com/user-attachments/assets/9ccdbfae-cd3f-43af-9759-cddcfb599498)
![ShopSmartUI6](https://github.com/user-attachments/assets/c3a3af4b-6818-4a96-b7e3-e6101a0ba7f4)
![ShopSmartUI5](https://github.com/user-attachments/assets/d1dbf714-6309-4c46-8f26-1753f531645c)
![ShopSmartUI4](https://github.com/user-attachments/assets/9f9f0026-2def-4736-82e5-a4394402af51)
![ShopSmartUI3](https://github.com/user-attachments/assets/40a1946b-f42f-481f-99f6-328cc0197675)
![ShopSmartUI2](https://github.com/user-attachments/assets/20ae25ef-bcf4-480d-908e-3773e67cde96)
![ShopSmartUI1](https://github.com/user-attachments/assets/f1902000-9630-4072-943c-3435aa5fc9c0)

**Comment by yuvrajsinghgmx** [comment]
"+" button for adding new items will be at the bottom right corner of the app.

**Comment by yuvrajsinghgmx** [comment]
If anyone wants to contribute for the UI only then he/she may create a new issue.

**Comment by Amit-4186** [comment]
@yuvrajsinghgmx Somethings I wanted to point out -

- Some Contributors are changing code unnecessary by mistake or pushing old code without updating which is leading to problems.
- I already fixed backstack navigation #39 but somehow the problem came back #96.
- Also someone please try to fix #92 as it is causing problems to other features such as  #61 also.
- Anyone who knows how the data initializes / refreshes on the homescreen please fix it asap.

**Comment by yuvrajsinghgmx** [comment]
> @yuvrajsinghgmx Somethings I wanted to point out -
> 
> * Some Contributors are changing code unnecessary by mistake or pushing old code without updating which is leading to problems.
> * I already fixed backstack navigation [Issue: Redundant Navigation Stack Entries on Back Button Press #39](https://github.com/yuvrajsinghgmx/ShopSmart/issues/39) but somehow the problem came back [Issue with back navigation, UI and backend. #96](https://github.com/yuvrajsinghgmx/ShopSmart/issues/96).
> * Also someone please try to fix [Bug - Stop auto reloading/refreshing of shopping list (Home Screen). #92](https://github.com/yuvrajsinghgmx/ShopSmart/issues/92) as it is causing problems to other features such as  [Feature: Add Favourites page. #61](https://github.com/yuvrajsinghgmx/ShopSmart/issues/61) also.
> * Anyone who knows how the data initializes / refreshes on the homescreen please fix it asap.

Great work and observation @Amit-4186 you are really appreciated.
A viewmodel can be implemented to fetch data once the app loads and then can be observed.

**Comment by pratheekv39** [comment]
@yuvrajsinghgmx  I noticed that on the leaderboard , my pull request reagrding Issue #41 is not displaying . Why is it??? Also it is a level 3 issue , that is why I am concerned . Can you please look into it ?? Thanks...

**Comment by yuvrajsinghgmx** [comment]
> @yuvrajsinghgmx I noticed that on the leaderboard , my pull request reagrding Issue #41 is not displaying . Why is it??? Also it is a level 3 issue , that is why I am concerned . Can you please look into it ?? Thanks...

Check it once more.

**Comment by pratheekv39** [comment]
@yuvrajsinghgmx It is now visible . Thanks  :)

**Comment by Shreyansh1563** [comment]
@yuvrajsinghgmx  assign this issue to me i can do it

**Comment by yuvrajsinghgmx** [comment]
Avinash-Codes
@iAmAjayTeli
@yasheela-alla
@Shreyansh1563
@rajdeepchakraborty-rc
@Yashvardhan-17
@Farhan-Ahmad01
@EvanSingee
@Satyajit0003
@J-B-Mugundh
@Nikhil0-3
@ark0078
@AnleaMJ
@Aman-G-upta
@Ankesh-erek
@Rohityadav9575
@Varsha567
@AndroidLord
@23WH1A0507
@KiranBaliga
@milansamuel609
@Muhasif-Hafiz
@rees8
@Shariq2003
@Shasha004
@aditya07389

**Comment by yuvrajsinghgmx** [comment]
Hi Everyone new issues are open go checkout and ask for assignment if you feel like working on it.
Max time for a
 level 1 issue is 1 day 
Level 2 - 2 days 
Level 3 - 3 days 

If the issue is not resolved within these limits other contributors may get assigned and PR will not be merged.

**Comment by yuvrajsinghgmx** [comment]
Hi Contributors please close the issues which you have completed.

**Comment by yuvrajsinghgmx** [comment]
ThankYou Contributors !!
and 
Beeeeessssttt of Luckkk for future.

**Comment by milansamuel609** [comment]
> ThankYou Contributors !! and Beeeeessssttt of Luckkk for future.

Thank you @yuvrajsinghgmx 😊

**Comment by rajdeepchakraborty-rc** [comment]
> ThankYou Contributors !! and Beeeeessssttt of Luckkk for future.

@yuvrajsinghgmx Thanks a lot for providing us the opportunity to contribute to your repository.

**Comment by pratheekv39** [comment]
Thank you for everything @yuvrajsinghgmx . ❤️

**Comment by Ankesh-erek** [comment]
THANK YOU @yuvrajsinghgmx . I have learnt many things from this project.

**Comment by rees8** [comment]
> ThankYou Contributors !! and Beeeeessssttt of Luckkk for future.

Thanks a lot @yuvrajsinghgmx. As a beginner to Kotlin, I got to learn a lot from your project.
