### ISSUE TITLE
Want to add some rules for the Contribution part so that good contributions are welcome and the process by which one can do PR..

### ISSUE THREAD

**Issue by ark0078** [yuvrajsinghgmx/ShopSmart#42]
Kindly assign me this issue @yuvrajsinghgmx @Rohityadav9575 @sanjay-kv @rees8 @Avinash-Codes @Ankesh-erek

**Comment by yuvrajsinghgmx** [comment]
Can you tell exactly what rules you want to add ?

**Comment by ark0078** [comment]
@yuvrajsinghgmx want to add the community guidelines,participants guidelines so that holistic approach is mantained

**Comment by Muhasif-Hafiz** [comment]
@yuvrajsinghgmx  I think it is a good idea

**Comment by yuvrajsinghgmx** [comment]
@ark0078 Go Ahead!

**Comment by ark0078** [comment]
@yuvrajsinghgmx please add gssoc-ext label too

**Comment by ark0078** [comment]
#53 updated..kindly merge it after a thorough review..hope this helps
@yuvrajsinghgmx

**Comment by ark0078** [comment]
@yuvrajsinghgmx thanks man...I hope this contribution adds value to this project?
