### ISSUE TITLE
Title: Add sorting and search functionality to shopping list

### ISSUE THREAD

**Issue by Shreyansh1563** [yuvrajsinghgmx/ShopSmart#54]
**Description:**
Add sorting options to the shopping list by name and date added. Implement a search bar to filter items based on keywords.

> @yuvrajsinghgmx Please assign me this issue as i have experience in android development with kotlin. also please add Hacktoberfest and Gssoc labels.

**Comment by yuvrajsinghgmx** [comment]
@Shreyansh1563 Just add a search icon which opens a search bar and products start getting sorted as the keywords are entered.

**Comment by Farhan-Ahmad01** [comment]
Hi Shreyansh, I've been tasked with working on the Top App bar, which will include the search button. Since you're working on implementing the search button, could you please update me on your progress so that I can proceed with implementing the top app bar?

**Comment by Shreyansh1563** [comment]
> Hi Shreyansh, I've been assigned to work on the Top App bar, which will include the search button. Since you're working on implementing the search button, could you please update me on your progress so that I can proceed with implementing the top app bar?

@Farhan-Ahmad01 Go ahead with with your work. I am adding the search button below the Top App Bar on the main screen.

**Comment by Farhan-Ahmad01** [comment]
I've finished my part and also made a PR. If you're still working on it, please consider adding the search feature to the top bar search icon. It won't make any difference. Placing it below the top bar would not result in a clean UI.
