### ISSUE TITLE
"ShopSmart" text 

### ISSUE THREAD

**Issue by yuvrajsinghgmx** [yuvrajsinghgmx/ShopSmart#59]
The topbar takes too much space and i think we have two approaches to solve it.

1) A Creative Idea about the topbar.
2) Simply reduce the space.

If anyone want to proceed with the first one then he/she must provide a brief and will be also prioritized for this only issue.

**Comment by Farhan-Ahmad01** [comment]
Or we can just reduce the extra space taken by the Top-App bar.

**Comment by Amit-4186** [comment]
@yuvrajsinghgmx Can i implement auto hiding top app bar on scrolling? If yes the please assign me the issue.

**Comment by yuvrajsinghgmx** [comment]
> I also noticed it and would be interested in working on it. The top bar is currently simple. We can enhance it by adding a search button for users to search for items and update it when a user selects items. When the user selects items, the top bar changes to show the number of selected items and the delete button. We can implement something similar to this. ![top id](https://private-user-images.githubusercontent.com/150573213/374330109-2120146b-4dc8-4ae6-b14b-d9a3e793d0bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODU4OTgsIm5iZiI6MTcyODM4NTU5OCwicGF0aCI6Ii8xNTA1NzMyMTMvMzc0MzMwMTA5LTIxMjAxNDZiLTRkYzgtNGFlNi1iMTRiLWQ5YTNlNzkzZDBiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxMTA2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjE0ZDRkMGE3MDYxY2QxNzUyOTYxNTc5NTE3YmIyODY2MzQ4NDJkYTc0ZGJmYjY1MDMxNDViYTFkYWI5NzIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3XiVO-GsYbY4OR7BQ8g2zefrGvToIN523vpHf098CVU)

We can introduce this.

**Comment by Farhan-Ahmad01** [comment]
Ok then please assign it to me, and I'll work on it.

**Comment by yuvrajsinghgmx** [comment]
#54 is working on the search feature so please keep this in mind.
I am assigning this to you.

**Comment by Farhan-Ahmad01** [comment]
Ok, I'll talk to him, there won't be any conflict.

**Comment by Farhan-Ahmad01** [comment]
I apologize for being late due to my midterms.
I encountered some issues while improving the top-app bar. Changing the height of the top bar looked so straight but it wasn't that easy. I tried a lot, but couldn't figure it out. It will take more time than I thought I guess.
Also, we don't get the same default color in the top bars as it is implemented in the Smart-Bottom navigation bar, so I left it as default for now.
I am making a PR please take a look at it.
