### ISSUE TITLE
Improving UI of Main Screen

### ISSUE THREAD

**Issue by yuvrajsinghgmx** [yuvrajsinghgmx/ShopSmart#6]

**Comment by Satyajit0003** [comment]
i will work on it

**Comment by yuvrajsinghgmx** [comment]
@Satyajit0003 I saw your improvements but that were not up to the mark please dont use image for background and the color behind the app name must be a single color it should have no gradience. Please Sync the repo once before restarting.

**Comment by Satyajit0003** [comment]
ok

**Comment by Satyajit0003** [comment]
![Uploading WhatsApp Image 2024-10-02 at 8.10.02 PM.jpeg…]()
is this ok

**Comment by yuvrajsinghgmx** [comment]
UI is improved already please  update your fork.
