### ISSUE TITLE
Feature: Add Favourites page.

### ISSUE THREAD

**Issue by Amit-4186** [yuvrajsinghgmx/ShopSmart#61]
To implement favourite button on shopping items list and add a favourites page on navigation.

> @yuvrajsinghgmx Please Assign this to me along with labels.

**Comment by yuvrajsinghgmx** [comment]
@Amit-4186 please refer to #4 for further improvements and changes.

**Comment by Shreyansh1563** [comment]
@yuvrajsinghgmx  if no one is working you can assign this issue to me

**Comment by yuvrajsinghgmx** [comment]
@Shreyansh1563  Any Update ??

**Comment by Shreyansh1563** [comment]
@yuvrajsinghgmx I'm currently working on it. Please label it as Level 3, as I need to design not only the UI but also the logic for the favorites page

**Comment by yuvrajsinghgmx** [comment]
Go Ahead ☺️👍

**Comment by Shreyansh1563** [comment]
@yuvrajsinghgmx I've already submitted this. If you'd like me to make any changes, please let me know; otherwise, you can close this issue.
