### ISSUE TITLE
Enhancement: Change the list ui to two-column Lazy grid.

### ISSUE THREAD

**Issue by Amit-4186** [yuvrajsinghgmx/ShopSmart#62]
Implement home screen list view like this.

![Screenshot_2024-10-08-14-28-23-88_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/d16ff6b2-3d66-4162-90b9-6f2eaecfab46)

@yuvrajsinghgmx Please assign this to me.

**Comment by yuvrajsinghgmx** [comment]
Dont forget the checkbox icon which deletes the item.

**Comment by Amit-4186** [comment]
> Dont forget the checkbox icon which deletes the item.

Ofcourse.
