### ISSUE TITLE
Not able to navigate to Home screen after clicking the  'Checkout' button.  

### ISSUE THREAD

**Issue by PrakashIrom** [yuvrajsinghgmx/ShopSmart#63]
After adding the items and when clicked on the 'Checkout' button, user cannot navigate to the Home screen. I think it has something to do with Navigation.

@yuvrajsinghgmx Please allow me to fix this issue.

**Comment by yuvrajsinghgmx** [comment]
The arrow button at the top left corner takes back to home screen.
But if you want to do this you can add a functionality where back button takes use to the home screen.

**Comment by PrakashIrom** [comment]
Okay I get it, thank you for assigning me I will get this one done.
