### ISSUE TITLE
 Implement Shopping Cart Feature Instead of My Orders

### ISSUE THREAD

**Issue by Varsha567** [yuvrajsinghgmx/ShopSmart#68]
Currently, the My Orders section displays items that have not yet been ordered, which can create confusion for users. To enhance user experience and provide clarity, I propose implementing a dedicated Shopping Cart feature that separates items that are still in the cart from those that have already been ordered.

Could you please assign this to me?

**Comment by yuvrajsinghgmx** [comment]
@Varsha567 Any Update ??

**Comment by yuvrajsinghgmx** [comment]
HI @Varsha567 Please refer to #4 Once if you are working on this.

**Comment by Varsha567** [comment]
Hi @yuvrajsinghgmx 

Apologies for the delay in providing an update. I was caught up with some other work, but I am now focusing on completing the task. I'll refer to #4 as you suggested and will provide a more detailed update soon.

Thank you for your understanding!

**Comment by yuvrajsinghgmx** [comment]
> Hi @yuvrajsinghgmx 
> 
> Apologies for the delay in providing an update. I was caught up with some other work, but I am now focusing on completing the task. I'll refer to #4 as you suggested and will provide a more detailed update soon.
> 
> Thank you for your understanding!

Okay No Worries.
