### ISSUE TITLE
New Feature Price Estimation: Add price estimates for items to keep track of budgets.

### ISSUE THREAD

**Issue by Rohityadav9575** [yuvrajsinghgmx/ShopSmart#7]
allowing users to add the amount for each product and calculate the total amount of products added.

**Comment by Rohityadav9575** [comment]
Hi! I’m interested in working on this issue. Could you please add the "hacktoberfest","gossoc-ext" ,"new feature " label I think it will help in keeping the track of amount of item we added to our list. Thank you!

**Comment by yuvrajsinghgmx** [comment]
Please Start working on it after #6 is completed. I will assign this to you as soon as @Satyajit0003  completes #6 .

**Comment by Rohityadav9575** [comment]
Thanks, if is it possible that I can merge my changes first then @Satyajit0003 .Will improve the UI it will be nice because UI of amount feature will also improve . I already implemented the feature and push it on new branch  .only creating pull request remains.

**Comment by yuvrajsinghgmx** [comment]
Okay please create a pull request and & @Satyajit0003  look into this.
