### ISSUE TITLE
Search Page

### ISSUE THREAD

**Issue by yuvrajsinghgmx** [yuvrajsinghgmx/ShopSmart#74]
A page where user searches for an item and can see prices from various e-commerce sites such as Flipkart Amazon etc.

**Comment by Avinash-Codes** [comment]
Can you elaborate on this a bit, and explain what its benefits will be in our app?

**Comment by yuvrajsinghgmx** [comment]
Benefits to the user

1.  Comparison of Prices of an item from various E-Commerce Sites
2.  User can add the item from that site to our app with a  link.
----------- Users can keep track of their favorite items across various sites directly within the app. 
-----------It creates a personalized shopping experience, making it easier to return to and compare items 
-----------they’re interested in.
4.  A method of referral codes from our site when the item is bought on that site this adds a financial incentive to the app.
5. It will make our app feature rich

For Future 

1. Real Time Price Alerts if an item crosses a threshold set by user
2. Universal Wishlist
3. Data Collection Recommendation & Ads from various sites
