### ISSUE TITLE
add a sepearate contributers.md file

### ISSUE THREAD

**Issue by aditya07389** [yuvrajsinghgmx/ShopSmart#76]
Hey @yuvrajsinghgmx i can add up a contributors.ms file with beginner friendly steps , it will look more organized and easier for contributors to find the steps to contribute , it will potentially boost the engagement with your repo , kindly assign this to me with labels gssoc extd and hacktoberfest accepted

**Comment by aditya07389** [comment]
hey @yuvrajsinghgmx ill submit pr soon !!

**Comment by yuvrajsinghgmx** [comment]
@aditya07389 Any Update ??

**Comment by aditya07389** [comment]
yeah i have exam ill do it soon

**Comment by aditya07389** [comment]
by tom??
