### ISSUE TITLE
Add a Dark Mode Toggle

### ISSUE THREAD

**Issue by 23WH1A0507** [yuvrajsinghgmx/ShopSmart#77]
Implement a toggle switch to enable dark mode in the app, allowing users to switch between light and dark themes for better usability in low-light environments.

**Comment by Amit-4186** [comment]
@yuvrajsinghgmx sir why this is 3 level? Don't get me wrong but it would take only a button and a single line of code to do so.

**Comment by yuvrajsinghgmx** [comment]
Thanks for getting my attention there @Amit-4186.
and you are welcome to point out mistakes in future.

**Comment by 23WH1A0507** [comment]
I’ve implemented the Dark Mode toggle feature as discussed. Users can now easily switch between light and dark themes, enhancing usability in low-light environments. The feature remembers their preference for future visits.

Feel free to check it out and let me know if you have any feedback or suggestions!

**Comment by Amit-4186** [comment]
> I’ve implemented the Dark Mode toggle feature as discussed. Users can now easily switch between light and dark themes, enhancing usability in low-light environments. The feature remembers their preference for future visits.
> 
> Feel free to check it out and let me know if you have any feedback or suggestions!

The app utilizes material ui for theme so I thought it would be easy to implement a toggle button.  But in case if you want to store preference for future then it would require little more effort. Sorry for overseeing it. I also worked on theming so in case you can ask me for suggestions or queries related to it.

**Comment by yuvrajsinghgmx** [comment]
@23WH1A0507 Can you please share the screen shot or a video of functioning you have added to the app and the dark mode toggle.

**Comment by yuvrajsinghgmx** [comment]
@Amit-4186 Would you like to work on this ??

**Comment by Jaswithadabbiru** [comment]
Hi @23WH1A0507 ! I’m interested in helping with the Dark Mode toggle feature. I think it would greatly enhance the user experience, especially for those who use the app in low-light environments. 

I’d like to confirm a couple of things:
1. Are there any specific design guidelines or preferences for the toggle switch?
2. Should the dark mode be implemented globally, or are there specific components/pages you want to focus on?

Looking forward to your response!!

**Comment by Amit-4186** [comment]
> @Amit-4186 Would you like to work on this ??

I would have loved to work on the feature but some things to i wanted to point. 

- Every contributer is changing the theme according to them while changing the UI.
- No benefit of changing theme or contributing anything related to theme.
- It would be better to finally set the theme when the UI will be finalized.
- Or else the contributers should not implement there own color / theme to any composable.

**Comment by yuvrajsinghgmx** [comment]
> > @Amit-4186 Would you like to work on this ??
> 
> I would have loved to work on the feature but some things to i wanted to point.
> 
> * Every contributer is changing the theme according to them while changing the UI.
> * No benefit of changing theme or contributing anything related to theme.
> * It would be better to finally set the theme when the UI will be finalized.
> * Or else the contributers should not implement there own color / theme to any composable.

Yes you are right while fixing some problems i also observed that contributors are adding there own color /theme but the issue was about a toggle switch.
