### ISSUE TITLE
The "Item Add" button disappears after deleting all the product items from the home screen.

### ISSUE THREAD

**Issue by Farhan-Ahmad01** [yuvrajsinghgmx/ShopSmart#83]
After removing all items from the home screen, including the Checkout button, the "add" button also disappears, preventing us from adding items.

The "Checkout/Add" button will only appear on the screen when there are items present.
![Screenshot 2024-10-11 001207](https://github.com/user-attachments/assets/eef65e04-2f6f-41f4-8172-c4e9f9da5592)

After deleting all the items, the "add" button disappears, and we are no longer able to add more items.
![Screenshot 2024-10-11 001215](https://github.com/user-attachments/assets/e6a0aecf-7326-4b98-b7c4-dced36052270)

**Comment by yuvrajsinghgmx** [comment]
It is resolved already please sync your project.
