### ISSUE TITLE
Checkout Button/Checkout Screen does not react according to selected items.

### ISSUE THREAD

**Issue by Farhan-Ahmad01** [yuvrajsinghgmx/ShopSmart#85]
-The checkout button doesn't display the total amount of selected items. It shows the total of all items without selecting, that need to be fixed.
![All Item total button](https://github.com/user-attachments/assets/4175d919-556b-4188-8b29-1b3a0476f434)

-The checkout Screen displays all the items, while the user selects only a few items.
![Default CScreen](https://github.com/user-attachments/assets/c2218696-e060-408d-b7d1-c1fb9f2a8449)

**Comment by Farhan-Ahmad01** [comment]
Please assign me this issue, I would love to fix it.
I'm almost done with all the necessary improvements, including enhancing the checkout button pop-up for a cleaner UI look.

**Comment by Amit-4186** [comment]
@Farhan-Ahmad01 I think the check uncheck button is for deleting and not checking out. Check out if for all items.

**Comment by Farhan-Ahmad01** [comment]
Checkout simply means that you want to proceed further with your selected products, like reviewing them, the total price of the selected products and placing the order for the selected products.

**Comment by yuvrajsinghgmx** [comment]
The total amount is fine but what you can improve is when user starts selecting the total amount shows the total of selected items else for all items and same logic for checkout button too.

**Comment by Farhan-Ahmad01** [comment]
Yeah, I can do that. I also want to introduce a few enhancements, like the checkout button doesn't need to be displayed all the time. It must appear only when the user really wants to checkout and selects at least one item.
This will not only improve the user experience but also give a clean look to the UI. We can move the checkout Button to the action button on the top bar.

**Comment by Farhan-Ahmad01** [comment]
Something like this, using the floating button, because when the user is selecting items, he can't add items at the same time and we can use the checkout button instead.
![Screenshot 2024-10-11 175914](https://github.com/user-attachments/assets/6f2b1868-ebc0-4bcd-a76f-16709e29cb6d)
