### ISSUE TITLE
Modification of README.md file.

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [yuvrajsinghgmx/ShopSmart#87]
# Description of Issue

### 1) Add animated line separators and add GSSoC 2024 Extended accepted banner
I want to add animated line separators in the README.md file to make it look more attractive and readable. I would also like to add the GSSoC 2024 Extended accepted image for Contributors to know that this repository is officially accepted for GSSoC contribution.
![image](https://github.com/user-attachments/assets/4dd78a96-9066-4614-bba6-58dd654c3bf7)

### 2) Add a **Team section**
Add a Team Section for the Contributors to know who to refer to when they need help about the project.
![image](https://github.com/user-attachments/assets/fae867de-c89c-441c-82ba-4b0d6374ef39)

### 3) Updation of the Contributors section
The current Contributors section is the README.md file is not updated to the latest Contributors. I would like to update it and try to **automate** the process.

The current Contributors section is the README.md file is not updated to the latest Contributors.
![image](https://github.com/user-attachments/assets/8f40ca39-481a-404c-8a2e-141c3559d505)

I want to update it and try to automate it to mention all the current contributors:
![image](https://github.com/user-attachments/assets/b59099d5-f769-4a1b-835f-8968086fd812)

I would like to work on the issues in order to make this repository more scalable and readable for the contributors and other users. Please assign this issue to me under **level2** so that I can work on it.

**Comment by rajdeepchakraborty-rc** [comment]
@yuvrajsinghgmx Thanks for assigning me the issue. Also I would like to ask whether the issue shouldn't be assigned **level2**? Since I am adding a lot of features.

**Comment by yuvrajsinghgmx** [comment]
Please add only automation of Contributors. Thanks for your time
.

**Comment by rajdeepchakraborty-rc** [comment]
> Please add only automation of Contributors. Thanks for your time .

What about the other sections? The Team section will also help in making the project more accessible to the contributors

**Comment by rajdeepchakraborty-rc** [comment]
@yuvrajsinghgmx If you are worried about the level issue, no need to update it. I was just asking whether it should be **level2**. The final call will always be yours since this is your project. My primary aim is to contribute to projects to make them more accessible and scalable. The points are always a secondary thing.

**Comment by rajdeepchakraborty-rc** [comment]
@yuvrajsinghgmx Wanted to update you regarding the work. Here is how the team section is looking for you:
![image](https://github.com/user-attachments/assets/3907d910-5ccf-4a78-be32-7db26477019f)

Hope you like it.

**Comment by rajdeepchakraborty-rc** [comment]
These are the program acceptance banners. This will help the contributors know that your repository is participating in these programs:
![image](https://github.com/user-attachments/assets/7ba8ae95-e349-4a10-8fec-6492d287e67d)

**Comment by rajdeepchakraborty-rc** [comment]
And here is the updated Contributors section:
![image](https://github.com/user-attachments/assets/0e74dd0b-7b0a-432e-a4cd-3460a92dc714)

**Comment by rajdeepchakraborty-rc** [comment]
I am almost done with the major of the work. I will just add some finishing touches and open a PR soon and let you know.

**Comment by rajdeepchakraborty-rc** [comment]
I have opened a PR. Please review it when you are comfortable

**Comment by yuvrajsinghgmx** [comment]
You have done a Good Work @rajdeepchakraborty-rc .

**Comment by rajdeepchakraborty-rc** [comment]
> You have done Good Work @rajdeepchakraborty-rc .

Thanks a lot for the appreciation @yuvrajsinghgmx 
I hope this helps in making your project more user friendly for the contributors.

Also please assign the PR #94 to me.
