### ISSUE TITLE
SignIn and SignUp Screen

### ISSUE THREAD

**Issue by Ayushh23** [yuvrajsinghgmx/ShopSmart#89]
I want to add Signin and Signup screen to get the proper data of user for showing in the profile area .

Please assign me this task with the tag of gssoc-ext

**Comment by yuvrajsinghgmx** [comment]
Please Start with the Frontend Part First.

**Comment by Ayushh23** [comment]
okay !!

**Comment by Ayushh23** [comment]
here is the frontend part

**Comment by yuvrajsinghgmx** [comment]
Hi @Ayushh23 please refer to #4 Once and tell me about your queries here.
