### ISSUE TITLE
Auth Page

### ISSUE THREAD

**Issue by yuvrajsinghgmx** [yuvrajsinghgmx/ShopSmart#9]
Creating  a new page which displays app logo,name and a button which says Continue with Google only the FrontEnd part.

**Comment by Harshmhajn** [comment]
Hi! May I work on this issue? Please assign it to me. Also, could you kindly add the @gssoc tag and the appropriate level tag? Thank you!

**Comment by AnleaMJ** [comment]
I'd like to work on this @yuvrajsinghgmx. Please add the appropriate gssoc-ext tags too. Thank you.

**Comment by yuvrajsinghgmx** [comment]
@AnleaMJ You can start wroking now on this.

**Comment by yuvrajsinghgmx** [comment]
Any Update ??

**Comment by DevSahil12** [comment]
i would like to work on this @yuvrajsinghgmx

**Comment by yuvrajsinghgmx** [comment]
@DevSahil12 You may create a new issue. @AnleaMJ is already assigmed to this one.

**Comment by AnleaMJ** [comment]
Good Afternoon @yuvrajsinghgmx. I'm working on the auth page. I'd like to get a high-quality image of the logo and the font required for the name 'ShopSmart'. Thank you.

**Comment by yuvrajsinghgmx** [comment]
Hi @AnleaMJ Good Afternoon i have attached image of the logo of maximum quality i can get , and the font used in logo was customised one so it cant be shared. You can use Anton or Oswald as
![Logo2](https://github.com/user-attachments/assets/8232da59-9b70-4b2e-a1d1-8301bfc9f19e)
![Logo1](https://github.com/user-attachments/assets/2a857dd5-4e85-4cb0-bc00-ad25acd2602f)
 they look similar or you may use a regular font.

**Comment by AnleaMJ** [comment]
Hello @yuvrajsinghgmx, I've made a pull request. Kindly review it.

**Comment by yuvrajsinghgmx** [comment]
Will do it .

**Comment by yuvrajsinghgmx** [comment]
> Much appreciated if I get level 2 points for the work 😊

Sure 😊
