### ISSUE TITLE
Bug - Stop auto reloading/refreshing of shopping list (Home Screen).

### ISSUE THREAD

**Issue by Amit-4186** [yuvrajsinghgmx/ShopSmart#92]
Whenever navigating to another screen, the home screen starts to refresh leading to problems.
Here is the preview -

https://github.com/user-attachments/assets/d2b08c7a-365b-4007-bf68-bd7f340e910a

Someone please fix it as issue #61 can't be done without it.

**Comment by yuvrajsinghgmx** [comment]
@Amit-4186  #4 Once and clarify your queries if you have any.

**Comment by AndroidLord** [comment]
Please assign this issue to me

**Comment by yuvrajsinghgmx** [comment]
@Amit-4186 The bug is fixed.
