### ISSUE TITLE
UI Fix

### ISSUE THREAD

**Issue by yuvrajsinghgmx** [yuvrajsinghgmx/ShopSmart#95]
Fixing UI for all the completed pages as in #4.
Previous contributors will be preffered.

**Comment by Farhan-Ahmad01** [comment]
Do we have to fix only the UI for now?

**Comment by Farhan-Ahmad01** [comment]
I can work on it.

**Comment by yuvrajsinghgmx** [comment]
Yes for now UI only and functioning for those which are implemented already.

**Comment by Farhan-Ahmad01** [comment]
Ok, I'll work on it.

**Comment by yuvrajsinghgmx** [comment]
> Ok, I'll work on it, please assign it to me.

Please do it ASAP.
