### ISSUE TITLE
Issue with back navigation, UI and backend.

### ISSUE THREAD

**Issue by iAmAjayTeli** [yuvrajsinghgmx/ShopSmart#96]
There is issue in back navigation .
It keeps opening the previous screen again and again
Here is the detailed explanation video of the  issue:-

https://github.com/user-attachments/assets/93a96342-5b8a-4eae-a646-2ea06b0cc83b

Also  the button navigation is also not looking good, and TopAppBar is not at the appropriate place and also the setting part is not working which is on the profile section and the placeholder image that is shown is not svg image and while i choose the profile picture the image cropper is not integrated. 

Here is the screenshot:-
![TopActionBar issue](https://github.com/user-attachments/assets/b0ea5745-6daf-4191-a4a9-16cda24664ca)

I can improve all UI and backend part and integrate the necessary libraries and make the app more beautiful. 

@yuvrajsinghgmx please assign this improvement to me.

**Comment by yuvrajsinghgmx** [comment]
Please refer to #4 Once.

**Comment by yuvrajsinghgmx** [comment]
@iAmAjayTeli Please Fix these ASAP.

**Comment by iAmAjayTeli** [comment]
> @iAmAjayTeli Please Fix these ASAP.

The UI should be like this ,right?@yuvrajsinghgmx 
:-https://github.com/yuvrajsinghgmx/ShopSmart/issues/4#issuecomment-2408933389

**Comment by yuvrajsinghgmx** [comment]
> > @iAmAjayTeli Please Fix these ASAP.
> 
> We have to improve UI design like this ,right?@yuvrajsinghgmx :-[#4 (comment)](https://github.com/yuvrajsinghgmx/ShopSmart/issues/4#issuecomment-2408933389)

Yes you are right the backend of the List page is working perfect you just need to work on improving the UI of List Page as in #4 with some improvements.

**Comment by iAmAjayTeli** [comment]
@yuvrajsinghgmx  yaa i currently fixing the UI of the Help and Support and will make pull request in some time today.

**Comment by Shreyansh1563** [comment]
@iAmAjayTeli If you aren't planning to work on the issue i would like to work on it. Please inform me in such case. Also this issue needs a simple change in navigation logic so tell me in case if  you want help.

**Comment by yuvrajsinghgmx** [comment]
@iAmAjayTeli Should i assign this to someone else ?

**Comment by yuvrajsinghgmx** [comment]
@Shreyansh1563 Should i assign this to you ???

**Comment by Shreyansh1563** [comment]
@yuvrajsinghgmx  yes you can assign this issue to me I am glad to work on it
