### ISSUE TITLE
HomePage (UI)

### ISSUE THREAD

**Issue by yuvrajsinghgmx** [yuvrajsinghgmx/ShopSmart#97]
Complete HomePage **UI Design** as in #4.

**Comment by rees8** [comment]
Could you let me know the exact emulator device that you're using @yuvrajsinghgmx ? I faced quite a lot of issues last time probably because of a different API.
Other than that, for implementing this UI, it can be implemented by introducing XML files for activity_main, and dummy products listed on home page (will be efficient if RecyclerView is used for products).
I am not quite familiar with API integration and as this is only UI implementation, I would go for this approach.
I can try and take up on this task, if I'm facing issues on my device, I'll notify ASAP so that someone else can pick up on this task.

**Comment by Amit-4186** [comment]
> Could you let me know the exact emulator device that you're using @yuvrajsinghgmx ? I faced quite a lot of issues last time probably because of a different API. Other than that, for implementing this UI, it can be implemented by introducing XML files for activity_main, and dummy products listed on home page (will be efficient if RecyclerView is used for products). I am not quite familiar with API integration and as this is only UI implementation, I would go for this approach. I can try and take up on this task, if I'm facing issues on my device, I'll notify ASAP so that someone else can pick up on this task.

Hey @rees8, I think you are not familiar with jetpack compose UI. Try to implement the UI by jetpack compose for which you must be familier with kotlin.

**Comment by rees8** [comment]
Oh okay. I mainly use Java while working on Android Studio, but I did familiarize myself with a bit of Kotlin. Then, maybe for now I can work on smaller tasks, once I become more comfortable, I'll pick up on the bigger tasks. Till then, you can leave this open for someone more experienced so as to not disrupt the workflow.

**Comment by yuvrajsinghgmx** [comment]
> Oh okay. I mainly use Java while working on Android Studio, but I did familiarize myself with a bit of Kotlin. Then, maybe for now I can work on smaller tasks, once I become more comfortable, I'll pick up on the bigger tasks. Till then, you can leave this open for someone more experienced so as to not disrupt the workflow.

Hi @rees8 You can keep an eye on the repo and raise an issue whenever you feel like you can do it.

**Comment by rees8** [comment]
Sure thing!

**Comment by yuvrajsinghgmx** [comment]
This is only UI part so @Shreyansh1563 please do it ASAP becuase backend integration will take time.

**Comment by Shreyansh1563** [comment]
@yuvrajsinghgmx please clarify for me whether by home page you mean ⬇️ this page or the page with a list of items which is the current homeScreen
![WhatsApp Image 2024-10-16 at 00 50 11_c42cb9bf](https://github.com/user-attachments/assets/84ac5c7b-acd2-4d4b-9765-f96398672edc)

**Comment by yuvrajsinghgmx** [comment]
> @yuvrajsinghgmx please clarify for me whether by home page you mean ⬇️ this page or the page with a list of items which is the current homeScreen ![WhatsApp Image 2024-10-16 at 00 50 11_c42cb9bf](https://private-user-images.githubusercontent.com/129738518/376762443-84ac5c7b-acd2-4d4b-9765-f96398672edc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMjA2OTUsIm5iZiI6MTcyOTAyMDM5NSwicGF0aCI6Ii8xMjk3Mzg1MTgvMzc2NzYyNDQzLTg0YWM1YzdiLWFjZDItNGQ0Yi05NzY1LWY5NjM5ODY3MmVkYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxOTI2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YWUzMTZhMmI2NDg5YzUwY2FlNGY4NTY3ZDBmYWY3ZTNkNzNiZGVkYjQzZDkwNDRiMGVlODFjMzczNGI4MmRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Hhy1VMJXrF6iOONCFFlYL-rX2mUn4Gcu760Yf5ml90Y)

THIS PAGE.
