### ISSUE TITLE
Product Details Page (UI)

### ISSUE THREAD

**Issue by yuvrajsinghgmx** [yuvrajsinghgmx/ShopSmart#98]
Complete Product Details Page UI as in #4.

**Comment by Amit-4186** [comment]
@yuvrajsinghgmx Please tell if the product details page is for home screen or favorites screen or both. Also please assign me this issue.

**Comment by yuvrajsinghgmx** [comment]
any update @Amit-4186 ??

**Comment by Shreyansh1563** [comment]
@yuvrajsinghgmx I can make ui assign this issue to me

**Comment by Shreyansh1563** [comment]
@yuvrajsinghgmx  GSSOC dose not counted this pull request please add labels on it or may be revert and merg it again
